/*
 * Copyright 2026 Khanh D. Nguyen, Hoang M. Truong, An T. Le.
 * Licensed under the Apache License, Version 2.0.
 * SPDX-License-Identifier: Apache-2.0
 */

#include "io/files.h"
#include "io/gguf.h"
#include "io/gguf_models.h"
#include <cstdio>
#include <dirent.h>
#include <fstream>
#include <map>
#include <mutex>
#include <sys/stat.h>

namespace tcpu {
namespace io {

namespace {

using Bytes = std::shared_ptr<const std::string>;

struct Mounted {
    int refs = 0;
    std::string sidecar;             // directory sidecars are read from
    std::map<std::string, Bytes> files;   // relative path -> generated bytes
};

// A seekable read-only view over shared bytes: the loaders seekg/tellg/peek
// like on a file, and C++17's istringstream would copy a multi-GB string.
class BytesBuf : public std::streambuf {
public:
    explicit BytesBuf(Bytes b) : bytes(std::move(b)) {
        char* p = const_cast<char*>(bytes->data());
        setg(p, p, p + bytes->size());
    }
protected:
    pos_type seekoff(off_type off, std::ios_base::seekdir dir, std::ios_base::openmode) override {
        char* base = eback();
        off_type at = dir == std::ios_base::beg ? off
                    : dir == std::ios_base::cur ? (gptr() - base) + off
                    : (egptr() - base) + off;
        if (at < 0 || at > egptr() - base) return pos_type(off_type(-1));
        setg(base, base + at, egptr());
        return pos_type(at);
    }
    pos_type seekpos(pos_type pos, std::ios_base::openmode m) override {
        return seekoff(off_type(pos), std::ios_base::beg, m);
    }
private:
    Bytes bytes;
};


std::mutex g_lock;
std::map<std::string, Mounted> g_mounts;

bool ends_with(const std::string& s, const char* suf) {
    const size_t n = std::char_traits<char>::length(suf);
    return s.size() >= n && s.compare(s.size() - n, n, suf) == 0;
}

std::string strip_slash(std::string p) {
    while (p.size() > 1 && p.back() == '/') p.pop_back();
    return p;
}

std::string parent(const std::string& p) {
    const size_t s = p.rfind('/');
    if (s == std::string::npos) return ".";
    return s == 0 ? "/" : p.substr(0, s);
}

// Large generated files are handed over once and dropped, so a load does not
// hold the adapter's copy and the loader's copy of every weight at the same
// time. Metadata stays, since a C API may re-read config.txt after the load.
constexpr size_t kConsumeBytes = 1 << 20;

} // namespace

std::string find_gguf(const std::string& path_in) {
    const std::string path = strip_slash(path_in);
    struct stat st;
    if (stat(path.c_str(), &st) != 0) return {};
    if (S_ISREG(st.st_mode)) return ends_with(path, ".gguf") ? path : std::string();
    if (!S_ISDIR(st.st_mode)) return {};
    DIR* d = opendir(path.c_str());
    if (!d) return {};
    std::string found;
    int n_gguf = 0, n_meta = 0;
    while (dirent* e = readdir(d)) {
        const std::string name = e->d_name;
        if (ends_with(name, ".gguf")) { n_gguf++; found = name; }
        else if (ends_with(name, ".meta")) n_meta++;
    }
    closedir(d);
    return n_gguf == 1 && n_meta == 0 ? path + "/" + found : std::string();
}

Mount::Mount(const std::string& path) : key(strip_slash(path)) {
    std::lock_guard<std::mutex> lk(g_lock);
    auto it = g_mounts.find(key);
    if (it != g_mounts.end()) {
        it->second.refs++;
        mounted = true;
        return;
    }
    const std::string file = find_gguf(key);
    if (file.empty()) return;

    Gguf g;
    std::string err;
    Mounted m;
    m.sidecar = file == key ? parent(key) : key;
    Files files;
    if (!g.open(file)) err = g.error();
    else adapt_gguf(g, Sidecar{m.sidecar}, files, err);
    if (!err.empty()) {
        std::fprintf(stderr, "vla-simd: %s\n", err.c_str());
        good = false;
        return;
    }
    for (auto& [rel, bytes] : files)
        m.files.emplace(rel, std::make_shared<const std::string>(std::move(bytes)));
    m.refs = 1;
    g_mounts.emplace(key, std::move(m));
    mounted = true;
}

Mount::~Mount() {
    if (!mounted) return;
    std::lock_guard<std::mutex> lk(g_lock);
    auto it = g_mounts.find(key);
    if (it != g_mounts.end() && --it->second.refs == 0) g_mounts.erase(it);
}

InFile::InFile(const std::string& path, std::ios::openmode mode) : std::istream(nullptr) {
    std::string disk = path;
    {
        std::lock_guard<std::mutex> lk(g_lock);
        for (auto& [prefix, m] : g_mounts) {
            if (path.size() <= prefix.size() + 1 || path.compare(0, prefix.size(), prefix) != 0 ||
                path[prefix.size()] != '/')
                continue;
            const std::string rel = path.substr(prefix.size() + 1);
            auto f = m.files.find(rel);
            if (f == m.files.end()) {
                disk = m.sidecar + "/" + rel;
                break;
            }
            buf = std::make_unique<BytesBuf>(f->second);
            if (f->second->size() >= kConsumeBytes) m.files.erase(f);
            rdbuf(buf.get());
            if (mode & std::ios::ate) seekg(0, std::ios::end);
            return;
        }
    }
    auto fb = std::make_unique<std::filebuf>();
    const bool opened = fb->open(disk, mode | std::ios::in) != nullptr;
    buf = std::move(fb);
    rdbuf(buf.get());
    if (!opened) setstate(std::ios::failbit);
}

} // namespace io
} // namespace tcpu
